name: Testing Self-Hosted Runner

on: 
  workflow_dispatch:

jobs:
    testing:
        runs-on: [
            self-hosted,
            Linux,
            X64,
            dev,
            vm
        ]
        steps:
            - name: Echo Content
              run: |
                echo ok
                sleep 1500s